common/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.utils.translation import gettext_lazy as _

from accounts import views as accounts_views
from accounts.forms import PasswordResetForm
from locations import views as loc_views
from news import views as news_views
from orchard import views

urlpatterns = [
    path('login/', accounts_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/new_user/', accounts_views.CreateAccountView.as_view(typ='user'),
        name='create_account_user'),
    path('accounts/new_owner/', accounts_views.CreateAccountView.as_view(typ='owner'),
        name='create_account_owner'),
    path('accounts/v/<token>/', accounts_views.VerifyAccountView.as_view(),
        name='account_verification'),
    path('accounts/<int:pk>/edit/', accounts_views.EditAccountView.as_view(),
        name='edit_account'),
    path('accounts/<int:pk>/delete/', accounts_views.DeleteAccountView.as_view(),
        name='delete-account'),

    # Password reset views
    path('accounts/password_reset/',
        auth_views.PasswordResetView.as_view(
            template_name='accounts/password_reset_form.html', form_class=PasswordResetForm),
        name='password_reset'),
    path('accounts/password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('reset/done/',
        auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),

    path('accounts/<int:pk>/saved_search/', accounts_views.SavedSearchList.as_view(),
        name='savedsearch-list'),
    path('accounts/<int:pk>/bookings/', accounts_views.BookingsList.as_view(),
        name='bookings-list'),
    path('accounts/<int:pk>/productorders/', accounts_views.ProductOrdersList.as_view(),
        name='productorders-list'),
    path('i18n/setlang/<lang_code>/', accounts_views.set_language, name='set_language'),

    path('', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('about/taxes/', views.SimpleTemplateView.as_view(template_name='taxes.html', title=_("Gebührenreglement")),
        name='taxes'),
    path('about/impressum/', views.SimpleTemplateView.as_view(template_name='impressum.html', title="Impressum"),
        name='impressum'),
    path('about/safety/', views.SimpleTemplateView.as_view(template_name='safety.html', title=_("Safety Data Sheet")),
        name='safety'),

    path('map/', views.MapView.as_view(), name='map'),
    path('offer/', views.OfferView.as_view(), name='offer'),
    path('collect/', views.CollectView.as_view(), name='collect'),
    path('collect/save_search/', views.SearchSaveView.as_view(), name='search-save'),
    path('collect/save_search/delete/', views.SearchSaveDeleteView.as_view(),
        name='search-delete'),
    path('news/', news_views.NewsListView.as_view(), name='news'),
    path('orchard/new/', views.OrchardNewView.as_view(), name='orchard_new'),
    path('orchard/<int:pk>/', views.OrchardView.as_view(), name='orchard'),
    path('orchard/<int:pk>/sendmail/', views.OrchardContactSend.as_view(),
        name='orchard-sendmail'),
    path('orchard/<int:pk>/overview/', views.OrchardOverview.as_view(),
        name='orchard-overview'),
    path('orchard/<int:pk>/edit/', views.OrchardEditView.as_view(),
        name='orchard_edit'),
    path('orchard/<int:pk>/delete/', views.OrchardDeleteView.as_view(),
        name='orchard_delete'),

    # Orchard trees
    path('orchard/<int:pk>/tree/new/', views.TreeNewView.as_view(), name='tree_new'),
    path('orchard/<int:pk>/tree/<int:pk_tree>/', views.TreeDetailsView.as_view(),
        name='tree_details'),
    path('orchard/<int:pk>/tree/<int:pk_tree>/edit/', views.TreeEditView.as_view(),
        name='tree_edit'),
    path('orchard/<int:pk>/tree/<int:pk_tree>/copymodifs/', views.TreeCopyModifsView.as_view(),
        name='tree_copymodifs'),
    path('orchard/<int:pk>/tree/<int:pk_tree>/duplicate/', views.TreeDuplicateView.as_view(),
        name='tree_dup'),
    path('orchard/<int:pk>/tree/<int:pk_tree>/delete/', views.TreeDeleteView.as_view(),
        name='tree_delete'),

    # Orchard products
    path('orchard/<int:pk>/product/new/', views.ProductNewView.as_view(), name='product_new'),
    path('orchard/<int:pk>/product/<int:pk_product>/', views.ProductDetailView.as_view(),
        name='product_detail'),
    path('orchard/<int:pk>/map_details/', views.OrchardMapDetails.as_view(),
        name='orchard-map-details'),
    path('orchard/<int:pk>/product/<int:pk_product>/edit/', views.ProductEditView.as_view(),
        name='product_edit'),
    path('orchard/<int:pk>/product/<int:pk_product>/delete/', views.ProductDeleteView.as_view(),
        name='product_delete'),
    path('orchard/<int:pk>/productorder/<int:pk_order>/', views.ProductOrderDetailView.as_view(),
        name='productorder_detail'),
    path('products/', views.ProductListView.as_view(), name='product_list'),
    path('my_products/', views.ProductOwnView.as_view(), name='my-products'),
    path('my_orchards/', views.OrchardOwnView.as_view(), name='my-orchards'),

    path('tree/<int:pk>/map_details/', views.TreeMapDetails.as_view(),
        name='tree-map-details'),
    path('tree/<int:pk>/<int:year>/book/', views.TreeBookingView.as_view(),
        name='tree-book'),
    path('booking/delete/', views.BookingDeleteView.as_view(),
        name='booking-delete'),

    path('location_search/', loc_views.LocationSearchView.as_view(), name='location-search'),

    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    # Should be an Apache alias in production
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

accounts/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _


class MyUserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)
    email_confirmed = models.BooleanField(default=False)
    language = models.CharField(_("Language"), max_length=5, choices=settings.LANGUAGES)
    street = models.CharField(_("Street"), max_length=150, blank=True)
    pcode = models.CharField(_("Postal code"), max_length=5)
    city = models.CharField(_("Locality"), max_length=50)
    phone = models.CharField(_("Phone"), max_length=30, blank=True)
    paiement_info = models.TextField(_("Paiement info"), blank=True,
        help_text=_("CCP, Bank account, IBAN… to receive paiements if you charge for fruits"))
    receive_news = models.BooleanField(
        _("I am interested to receive news from this site"), default=True
    )
    fruit_interest = models.ManyToManyField('orchard.TreeSpecies', blank=True, verbose_name=_("Fruit interests"))

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        if self.first_name or self.last_name:
            return " ".join([self.first_name, self.last_name])
        return self.email

    @cached_property
    def is_owner(self):
        return self.orchard_set.exists()

    def deletable(self):
        # FIXME: currently, those links are protected, they should be 'serialized'
        # when the user object is deleted.
        return not self.booking_set.exists() and not self.productorder_set.exists()

    def get_address(self):
        """Concatenated street, pcode, city."""
        city = " ".join([self.pcode, self.city]).strip()
        if self.street:
            return "%s\n%s" % (self.street, city)
        else:
            return city

accounts/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.views import LoginView as AuthLoginView
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.template import loader
from django.urls import reverse, reverse_lazy
from django.utils.http import url_has_allowed_host_and_scheme
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy, gettext as _

from django.views.generic import CreateView, DeleteView, ListView, UpdateView, View

from orchard.mail import send_mail
from orchard.views import TitleViewMixin

from . import forms
from .mailchimp import MailChimpList
from .models import User
from .utils import EmailVerifyTokenGenerator


class LoginView(TitleViewMixin, AuthLoginView):
    template_name = 'accounts/login.html'
    title = gettext_lazy("Login")


class CreateAccountView(CreateView):
    form_class = forms.UserCreationForm
    template_name = 'accounts/account.html'
    typ = None

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('home'))
        return super().get(request)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['typ'] = self.typ
        return kwargs

    def form_valid(self, form):
        response = super().form_valid(form)
        # Send confirmation email
        context = {
            'domain': get_current_site(self.request).domain,
            'token': EmailVerifyTokenGenerator().token_for_email(self.object.email),
            'protocol': 'https' if self.request.is_secure() else 'http',
        }
        body = loader.render_to_string("accounts/verification_email.txt", context, using='django-text')
        subject = _("MeinObstgarten email confirmation")
        send_mail(subject, body, settings.SITE_EMAIL, [self.object.email])
        return response

    def get_success_url(self):
        messages.success(self.request,
            _("Thanks for creating the account. An email has been sent to %s, "
              "please check your mailbox and follow the given link to confirm "
              "your address and be able to login on this site.") % self.object.email)
        return reverse('offer')


class OnOwnProfileMixin(UserPassesTestMixin):
    """
    On most profile pages, only the logged-in user or a superuser can access the
    page.
    """
    def test_func(self):
        return self.request.user.is_superuser or int(self.kwargs['pk']) == self.request.user.pk


class EditAccountView(OnOwnProfileMixin, UpdateView):
    model = User
    form_class = forms.UserChangeForm
    template_name = 'accounts/account.html'

    def get_initial(self):
        initial = super().get_initial()
        if not 'next_page' in self.initial:
            initial['next_page'] = self.request.META.get('HTTP_REFERER', "/")
        return initial

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['typ'] = 'owner' if self.object.is_owner else 'user'
        return kwargs

    def form_valid(self, form):
        self.object = form.save()
        next_url = form.cleaned_data['next_page']
        if url_has_allowed_host_and_scheme(next_url, allowed_hosts=[self.request.get_host()]):
            return HttpResponseRedirect(next_url)
        return HttpResponseRedirect(reverse('home'))


class VerifyAccountView(View):
    def get(self, request, *args, **kwargs):
        # Verify token, set user.email_confirmed, redirect with message
        email = EmailVerifyTokenGenerator().email_for_token(kwargs['token'])
        if email is None:
            messages.error(request, _("Sorry, the account verification failed."))
        else:
            account = get_object_or_404(User, email=email)
            account.email_confirmed = True
            account.save()
            login(request, account)
            messages.success(request, _("Your account was successfully confirmed!"))
        return HttpResponseRedirect(reverse('home'))


class DeleteAccountView(OnOwnProfileMixin, DeleteView):
    model = User
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        user = self.object
        # Test and warn if user has orchard/product order/booking linked.
        if user.orchard_set.count() > 0:
            messages.error(self.request, _("Sorry, you must delete your orchards before you can delete your account."))
            return HttpResponseRedirect(self.request.META.get('HTTP_REFERER', "/"))
        if user.productorder_set.filter(status='ordered').count() > 0:
            messages.error(
                self.request,
                mark_safe(_('Sorry, you have <a href="%s">pending orders</a>. Please cancel '
                  'them before you can delete your account.') % reverse(
                    'productorders-list', args=[user.pk]
                ))
            )
            return HttpResponseRedirect(self.request.META.get('HTTP_REFERER', "/"))
        if user.booking_set.filter(status='planned').count() > 0:
            messages.error(
                self.request,
                mark_safe(_('Sorry, you have planned <a href="%s">tree bookings</a>. '
                  'Please cancel them before you can delete your account.') % reverse(
                    'bookings-list', args=[user.pk]
                ))
            )
            return HttpResponseRedirect(self.request.META.get('HTTP_REFERER', "/"))
        # Archive product orders
        for order in user.productorder_set.all():
            order.archive(reason='User deleted his/her account')
        # Archive bookings
        for booking in user.booking_set.all():
            booking.archive(reason='User deleted his/her account')
        if user.email and user.receive_news:
            MailChimpList().remove_member(user.email)
        response = super().form_valid(form)
        messages.success(self.request, _("Your account was successfully deleted."))
        return response


class SavedSearchList(OnOwnProfileMixin, ListView):
    template_name = 'accounts/savedsearch_list.html'

    def get_queryset(self):
        return self.request.user.savedsearch_set.all()


class BookingsList(OnOwnProfileMixin, ListView):
    template_name = 'accounts/bookings_list.html'

    def get_queryset(self):
        return self.request.user.booking_set.all().select_related('tree__orchard')


class ProductOrdersList(OnOwnProfileMixin, ListView):
    template_name = 'accounts/productorders_list.html'

    def get_queryset(self):
        return self.request.user.productorder_set.all().order_by('status')


def set_language(request, lang_code):
    """
    Inspired from django.views.i18n and adapted to accept REST parameter
    """
    next_url = request.POST.get('next', request.GET.get('next'))
    if not next_url or not url_has_allowed_host_and_scheme(
        next_url,
        allowed_hosts={request.get_host()},
    ):
        next_url = request.META.get('HTTP_REFERER', "/")
    response = HttpResponseRedirect(next_url)

    response.set_cookie(settings.LANGUAGE_COOKIE_NAME, lang_code)
    if request.user.is_authenticated:
        request.user.language = lang_code
        request.user.save()
    return response

templates/accounts/account.html
{% extends "base.html" %}
{% load orchard %}

{% block content %}
<div class="generic-page">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-10 offset-md-1 col-lg-7">
                <h1 class="page-header">{% if form.instance.pk %}{% trans 'My account' %}{% else %}{% trans 'Create an account' %}{% endif %}</h1>

                {{ form.non_field_errors }}

                <form method="POST" action="">
                    {% csrf_token %}
                    {% if not form.instance.pk %}
                        {{ form.next_page }}
                    {% endif %}

                    <div class="row">
                        <div class="col-12 col-sm-6">
                            <div class="input-group">
                                {{ form.first_name|label_tag }}
                                <input type="text" id="id_first_name" name="{{ form.first_name.name }}" class="input-group__field" placeholder="{{ form.first_name.label }}" value="{{ form.first_name.value|default:'' }}">
                                {{ form.first_name.errors }}
                            </div>
                        </div>

                        <div class="col-12 col-sm-6">
                            <div class="input-group">
                                {{ form.last_name|label_tag }}
                                <input type="text" id="id_last_name" name="{{ form.last_name.name }}" class="input-group__field" placeholder="{{ form.last_name.label }}" value="{{ form.last_name.value|default:'' }}">
                                {{ form.last_name.errors }}
                            </div>
                        </div>

                        <div class="col-12">
                            <div class="input-group">
                                {{ form.email|label_tag }}
                                <input type="email" id="id_email" name="{{ form.email.name }}" class="input-group__field" placeholder="{{ form.email.label }}" value="{{ form.email.value|default:'' }}">
                                {{ form.email.errors }}
                            </div>
                        </div>

                        <div class="col-12">
                            <div class="input-group">
                                {{ form.language|label_tag }}
                                <select id="language" name="{{ form.language.name }}" class="input-group__field">
                                    <option value="">--------</option>
                                    {% for lang in LANGUAGES %}
                                        <option value="{{ lang.0 }}" {% if form.language.value == lang.0 %} selected {% endif %}>{% trans lang.1 %}</option>
                                    {% endfor %}
                                </select>
                                {{ form.language.errors }}
                            </div>
                        </div>

                        <div class="col-12">
                            <div class="input-group">
                                {{ form.street|label_tag }}
                                <input type="text" id="id_street" name="{{ form.street.name }}" class="input-group__field" placeholder="{{ form.street.label }}" value="{{ form.street.value|default:'' }}">
                                {{ form.street.errors }}
                            </div>
                        </div>

                        <div class="col-12 col-sm-6">
                            <div class="input-group">
                                {{ form.pcode|label_tag }}
                                <input type="text" id="pcode" name="{{ form.pcode.name }}" class="input-group__field" placeholder="{{ form.pcode.label }}" value="{{ form.pcode.value|default:'' }}">
                                {{ form.pcode.errors }}
                            </div>
                        </div>

                        <div class="col-12 col-sm-6">
                            <div class="input-group">
                                {{ form.city|label_tag }}
                                <input type="text" id="id_city" name="{{ form.city.name }}" class="input-group__field" placeholder="{{ form.city.label }}" value="{{ form.city.value|default:'' }}">
                                {{ form.city.errors }}
                            </div>
                        </div>

                        <div class="col-12">
                            <div class="input-group">
                                {{ form.phone|label_tag }}
                                <input type="text" id="id_phone" name="{{ form.phone.name }}" class="input-group__field" placeholder="{{ form.phone.label }}" value="{{ form.phone.value|default:'' }}">
                                {{ form.phone.errors }}
                            </div>
                        </div>

                        {% if form.paiement_info %}
                            <div class="col-12">
                                <div class="input-group">
                                    {{ form.paiement_info|label_tag }}
                                    <textarea id="id_payment-info" name="{{ form.paiement_info.name }}" class="input-group__field" placeholder="{{ form.paiement_info.label }}">{{ form.paiement_info.value|default:'' }}</textarea>
                                    {{ form.paiement_info.errors }}
                                </div>
                                <span class="helptext">{{ form.paiement_info.help_text }}</span>
                            </div>
                        {% endif %}

                        <div class="col-12">
                            <div class="input-group">
                                <label for="receive_news" class="custom-checkbox">
                                    <input class="custom-checkbox__input" type="checkbox" id="receive_news" name="{{ form.receive_news.name }}" {% if form.receive_news.value %} checked {% endif %}>
                                    <span class="custom-checkbox__label">{{ form.receive_news.label|cut:':' }}</span>
                                </label>
                                {{ form.receive_news.errors }}
                            </div>
                        </div>

                        <div class="col-12 fruit-interest-list">
                            <label class="input-group__label">{{ form.fruit_interest.label }}</label>
                            <div class="input-group row">
                                {% for item in form.fruit_interest.field.choices %}
                                    <div class="col-4">
                                        <label for="fruit_interest_{{ item.0 }}" class="custom-checkbox">
                                            <input
                                                type="checkbox"
                                                id="fruit_interest_{{ item.0 }}"
                                                class="custom-checkbox__input"
                                                name="{{ form.fruit_interest.name }}"
                                                value="{{ item.0 }}"
                                                {% if item.0|stringformat:'s' in form.fruit_interest.value|stringformat:'s' %} checked {% endif %}
                                            >
                                            <span class="custom-checkbox__label">{{ item.1 }}</span>
                                        </label>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>

                        {% if not form.instance.pk %}
                            <div class="col-12">
                                <div class="input-group">
                                    {{ form.password1|label_tag }}
                                    <input type="password" id="id_password1" name="{{ form.password1.name }}" class="input-group__field" placeholder="{{ form.password1.label }}">
                                    {{ form.password1.errors }}
                                </div>
                            </div>

                            <div class="col-12">
                                <div class="input-group">
                                    {{ form.password2|label_tag }}
                                    <input type="password" id="id_password2" name="{{ form.password2.name }}" class="input-group__field" placeholder="{{ form.password2.label }}">
                                    {{ form.password2.errors }}
                                    <span class="helptext"></span>{{ form.password2.help_text }}</span>
                                </div>
                            </div>
                        {% endif %}

                        <div class="col-12 col-sm-6">
                            <button type="submit" class="btn mb1r">{% if form.instance.pk %}{% trans 'Modify my account' %}{% else %}{% trans 'Create account' %}{% endif %}</button>
                        </div>
                        {% if form.instance.pk and form.instance.deletable %}
                            <div class="col-12 col-sm-6 justify-content-end--md">
                                <button type="submit" formaction="{% url 'delete-account' form.instance.pk %}" data-confirm="{% trans 'Do you really want to delete your account?' %}" class="btn is-secondary mb1r">{% trans 'Delete my account' %}</button>
                            </div>
                        {% endif %}
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/bookings_list.html
{% extends "base.html" %}
{% load orchard %}

{% block extra_head %}
<style type="text/css">
span.buttons { margin-left: 5em; cursor: pointer; }
</style>
<script type="text/javascript">
document.addEventListener("DOMContentLoaded", function(event) {
    var links = document.getElementsByClassName('del-link');
    for (i = 0; i < links.length; i++) {
        links[i].addEventListener('click', function (ev) {
            ev.preventDefault();
            if (confirm('{% trans "Do you really want to delete this booking?" %}')) {
                var form = document.getElementById('delete-form');
                form.bookingid.value = this.dataset.bookingid;
                form.submit();
            }
        });
    }
});
</script>
{% endblock %}

{% block content %}
<div class="generic-page">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-10 offset-md-1 col-lg-7">
                <h1 class="page-header">{% trans "My bookings" %}</h1>
            </div>
            <div class="col-12 col-md-10 offset-md-1 col-lg-7">
                <form id="delete-form" method="post" action="{% url 'booking-delete' %}">{% csrf_token %}
                    <input type="hidden" name="bookingid">
                    <ul class="data-list">
                    {% for booking in object_list %}
                        <li class="data-list-item">
                            <div class="data-list-item__helper">
                                <h2 class="data-list-item__title">
                                    {% blocktrans with tree=booking.tree orchard=booking.tree.orchard url=booking.tree.orchard.get_absolute_url %}{{ tree }} in orchard <a href="{{ url }}">{{ orchard }}</a>.{% endblocktrans %}
                                </h2>
                                <span class="data-list-item__meta">
                                    {% if booking.tree.fruit_quantity != '-' %} {{ booking.tree.fruit_quantity }} {% endif %}
                                    ({{ booking.tree|pick_date_string:booking.year }})
                                    {% if booking.tree.price %}, {{ booking.tree.price_string }} {% endif %}
                                </span>
                            </div>
                            {% if booking.can_delete %}
                                <div class="buttons">
                                    <img class="del-link" data-bookingid="{{ booking.pk }}" src="{% static 'img/icon-deletelink.svg' %}" title="{% trans 'Delete' %}" width="22">
                                </div>
                            {% endif %}
                        </li>
                    {% empty %}
                        <li class="message is-warning" style="list-style: none;">{% trans 'No bookings yet.' %}</li>
                    {% endfor %}
                    </ul>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
    <div class="generic-page login-page">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-10 offset-md-1 col-lg-7">
                    <h1 class="page-header">{% trans "Login" %}</h1>

                    <h2 class="form-title">{% trans "Do you already have an account?" %}</h2>

                    {{ form.non_field_errors }}

                    <form action="" method="POST" class="form">
                        {% csrf_token %}

                        <div class="input-group">
                            <label for="email" class="input-group__label sr-only">{% trans "E-Mail" %}</label>
                            <input type="email" id="email" name="username" class="input-group__field" placeholder='{% trans "E-Mail" %}'>
                            {{ form.username.errors }}
                        </div>

                        <div class="input-group">
                            <label for="password" class="input-group__label sr-only">{% trans "Password" %}</label>
                            <input type="password" id="password" name="password" class="input-group__field" placeholder='{% trans "Password" %}'>
                            {{ form.password.errors }}
                        </div>

                        <div class="form__password-reset-link">
                            <a href="{% url 'password_reset' %}">{% trans 'Forgotten your password or username?' %}</a>
                        </div>

                        {% if next %}
                            <input type="hidden" name="next" value="{{ next }}">
                        {% endif %}

                        <button type="submit" class="btn">{% trans 'Login' %}</button>
                    </form>

                    <div class="login-registration-section">
                        <h2 class="form-title">{% trans 'Don’t have an account? Register now!' %}</h2>
                        <a href="{% url 'create_account_user' %}" class="btn">{% trans "Create an account" %}</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}