common/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.utils.translation import gettext_lazy as _

from accounts import views as accounts_views
from accounts.forms import PasswordResetForm
from locations import views as loc_views
from news import views as news_views
from orchard import views

urlpatterns = [
    path('login/', accounts_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/new_user/', accounts_views.CreateAccountView.as_view(typ='user'),
        name='create_account_user'),
    path('accounts/new_owner/', accounts_views.CreateAccountView.as_view(typ='owner'),
        name='create_account_owner'),
    path('accounts/v/<token>/', accounts_views.VerifyAccountView.as_view(),
        name='account_verification'),
    path('accounts/<int:pk>/edit/', accounts_views.EditAccountView.as_view(),
        name='edit_account'),
    path('accounts/<int:pk>/delete/', accounts_views.DeleteAccountView.as_view(),
        name='delete-account'),

    # Password reset views
    path('accounts/password_reset/',
        auth_views.PasswordResetView.as_view(
            template_name='accounts/password_reset_form.html', form_class=PasswordResetForm),
        name='password_reset'),
    path('accounts/password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('reset/done/',
        auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),

    path('accounts/<int:pk>/saved_search/', accounts_views.SavedSearchList.as_view(),
        name='savedsearch-list'),
    path('accounts/<int:pk>/bookings/', accounts_views.BookingsList.as_view(),
        name='bookings-list'),
    path('accounts/<int:pk>/productorders/', accounts_views.ProductOrdersList.as_view(),
        name='productorders-list'),
    path('i18n/setlang/<lang_code>/', accounts_views.set_language, name='set_language'),

    path('', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('about/taxes/', views.SimpleTemplateView.as_view(template_name='taxes.html', title=_("Gebührenreglement")),
        name='taxes'),
    path('about/impressum/', views.SimpleTemplateView.as_view(template_name='impressum.html', title="Impressum"),
        name='impressum'),
    path('about/safety/', views.SimpleTemplateView.as_view(template_name='safety.html', title=_("Safety Data Sheet")),
        name='safety'),

    path('map/', views.MapView.as_view(), name='map'),
    path('offer/', views.OfferView.as_view(), name='offer'),
    path('collect/', views.CollectView.as_view(), name='collect'),
    path('collect/save_search/', views.SearchSaveView.as_view(), name='search-save'),
    path('collect/save_search/delete/', views.SearchSaveDeleteView.as_view(),
        name='search-delete'),
    path('news/', news_views.NewsListView.as_view(), name='news'),
    path('orchard/new/', views.OrchardNewView.as_view(), name='orchard_new'),
    path('orchard/<int:pk>/', views.OrchardView.as_view(), name='orchard'),
    path('orchard/<int:pk>/sendmail/', views.OrchardContactSend.as_view(),
        name='orchard-sendmail'),
    path('orchard/<int:pk>/overview/', views.OrchardOverview.as_view(),
        name='orchard-overview'),
    path('orchard/<int:pk>/edit/', views.OrchardEditView.as_view(),
        name='orchard_edit'),
    path('orchard/<int:pk>/delete/', views.OrchardDeleteView.as_view(),
        name='orchard_delete'),

    # Orchard trees
    path('orchard/<int:pk>/tree/new/', views.TreeNewView.as_view(), name='tree_new'),
    path('orchard/<int:pk>/tree/<int:pk_tree>/', views.TreeDetailsView.as_view(),
        name='tree_details'),
    path('orchard/<int:pk>/tree/<int:pk_tree>/edit/', views.TreeEditView.as_view(),
        name='tree_edit'),
    path('orchard/<int:pk>/tree/<int:pk_tree>/copymodifs/', views.TreeCopyModifsView.as_view(),
        name='tree_copymodifs'),
    path('orchard/<int:pk>/tree/<int:pk_tree>/duplicate/', views.TreeDuplicateView.as_view(),
        name='tree_dup'),
    path('orchard/<int:pk>/tree/<int:pk_tree>/delete/', views.TreeDeleteView.as_view(),
        name='tree_delete'),

    # Orchard products
    path('orchard/<int:pk>/product/new/', views.ProductNewView.as_view(), name='product_new'),
    path('orchard/<int:pk>/product/<int:pk_product>/', views.ProductDetailView.as_view(),
        name='product_detail'),
    path('orchard/<int:pk>/map_details/', views.OrchardMapDetails.as_view(),
        name='orchard-map-details'),
    path('orchard/<int:pk>/product/<int:pk_product>/edit/', views.ProductEditView.as_view(),
        name='product_edit'),
    path('orchard/<int:pk>/product/<int:pk_product>/delete/', views.ProductDeleteView.as_view(),
        name='product_delete'),
    path('orchard/<int:pk>/productorder/<int:pk_order>/', views.ProductOrderDetailView.as_view(),
        name='productorder_detail'),
    path('products/', views.ProductListView.as_view(), name='product_list'),
    path('my_products/', views.ProductOwnView.as_view(), name='my-products'),
    path('my_orchards/', views.OrchardOwnView.as_view(), name='my-orchards'),

    path('tree/<int:pk>/map_details/', views.TreeMapDetails.as_view(),
        name='tree-map-details'),
    path('tree/<int:pk>/<int:year>/book/', views.TreeBookingView.as_view(),
        name='tree-book'),
    path('booking/delete/', views.BookingDeleteView.as_view(),
        name='booking-delete'),

    path('location_search/', loc_views.LocationSearchView.as_view(), name='location-search'),

    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    # Should be an Apache alias in production
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

orchard/models.py
import datetime
from collections import OrderedDict
from urllib.parse import urlencode

from django import forms
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.contrib.gis.db import models as gis_models
from django.contrib.gis.geos import MultiPoint
from django.contrib.postgres.fields import ArrayField
from django.contrib.staticfiles.storage import staticfiles_storage
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from colorful.fields import RGBColorField
from parler.models import TranslatableModel, TranslatedFields
from accounts.models import User
from locations.models import Location

APP_SRID = 2056  # Not to be changed lightly, as this would need migrations

YEAR_PERIOD_CHOICES = (
    ('01.01', _("Start of January")),
    ('01.15', _("Middle of January")),
    ('01.31', _("End of January")),
    ('02.01', _("Start of February")),
    ('02.15', _("Middle of February")),
    ('02.28', _("End of February")),
    ('03.01', _("Start of March")),
    ('03.15', _("Middle of March")),
    ('03.31', _("End of March")),
    ('04.01', _("Start of April")),
    ('04.15', _("Middle of April")),
    ('04.30', _("End of April")),
    ('05.01', _("Start of May")),
    ('05.15', _("Middle of May")),
    ('05.31', _("End of May")),
    ('06.01', _("Start of June")),
    ('06.15', _("Middle of June")),
    ('06.30', _("End of June")),
    ('07.01', _("Start of July")),
    ('07.15', _("Middle of July")),
    ('07.31', _("End of July")),
    ('08.01', _("Start of August")),
    ('08.15', _("Middle of August")),
    ('08.31', _("End of August")),
    ('09.01', _("Start of September")),
    ('09.15', _("Middle of September")),
    ('09.30', _("End of September")),
    ('10.01', _("Start of October")),
    ('10.15', _("Middle of October")),
    ('10.31', _("End of October")),
    ('11.01', _("Start of November")),
    ('11.15', _("Middle of November")),
    ('11.30', _("End of November")),
    ('12.01', _("Start of December")),
    ('12.15', _("Middle of December")),
    ('12.31', _("End of December")),
)

PAIEMENT_CHOICES = (
    ('adv', _('Advance paiement')),
    ('cash', _('Cash on site')),
)


class ArrayChoiceFormField(forms.TypedMultipleChoiceField):
    widget = forms.CheckboxSelectMultiple

    def __init__(self, *args, **kwargs):
        # Prevent the empty choice
        if kwargs['choices'] and kwargs['choices'][0][0] == '':
            kwargs['choices'] = kwargs['choices'][1:]
        super().__init__(*args, **kwargs)


class ChoiceArrayField(ArrayField):
    def formfield(self, **kwargs):
        # Patch from https://code.djangoproject.com/ticket/27704
        if self.base_field.choices and 'choices_form_class' not in kwargs:
            defaults = {
                'choices_form_class': ArrayChoiceFormField,
                'coerce': self.base_field.to_python,
            }
            defaults.update(kwargs)
            return self.base_field.formfield(**defaults)
        else:
            defaults = {
                'form_class': SimpleArrayField,
                'base_field': self.base_field.formfield(),
                'max_length': self.size,
            }
        defaults.update(kwargs)
        return super().formfield(**defaults)



class Photo(models.Model):
    image = models.ImageField(upload_to="photos")
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey()


class VisibleQuerySet(models.QuerySet):
    """visble(user) only shows public or user-owned orchards."""
    def visible(self, user):
        return self.filter(models.Q(is_public=True) | models.Q(owner__pk=user.pk))


class Orchard(models.Model):
    owner = models.ForeignKey(User, on_delete=models.PROTECT)
    name = models.CharField(_("Name"), max_length=100)
    is_public = models.BooleanField(_("This orchard is visible to the public"), default=True,
        help_text=_("By checking this box, the orchard and its products become visible "
                    "to the public. If it's unchecked, the orchard and its products are "
                    "\"private\" and no longer publicly visible."),
    )
    municipality = models.ForeignKey(Location, verbose_name=_("Municipality"),
        on_delete=models.PROTECT)
    description = models.TextField(_("Description"))
    real_owner_name = models.CharField(_("Name"), max_length=100, blank=True)
    real_owner_addr = models.TextField(_("Address"), blank=True)
    real_owner_phone = models.CharField(_("Phone"), max_length=30, blank=True)
    real_owner_email = models.EmailField(_('email address'), blank=True)
    real_owner_paiement_info = models.TextField(_("Paiement info"), blank=True,
        help_text=_("CCP, Bank account, IBAN… to receive paiements if you charge for fruits"))
    real_owner_is_contact = models.BooleanField(default=False)
    pick_details = models.TextField(_("Pick instructions"), blank=True,
        help_text=_("Describe here details about any available ladder, its look and location, "
                    "maybe an unlocking code, available containers, whether they can be took away, etc. "
                    "This text is only visible by people having booked picking a tree in this orchard.")
    )

    photos = GenericRelation(Photo)

    objects = VisibleQuerySet.as_manager()

    def __str__(self):
        return self.name + str(_(" (private)") if not self.is_public else "")

    def get_absolute_url(self):
        return reverse('orchard', args=[self.pk])

    def geojson(self, target_srid=None):
        center = self.center
        if target_srid and center.srid != target_srid:
            center.transform(target_srid)
        return {
            'type': 'Feature',
            'id': self.pk,
            'geometry': {
                'type': 'Point',
                'coordinates': center.coords,
            },
            'properties': {
                'pk': self.pk,
                'icon': self.icon,
            },
        }

    def get_contact(self):
        if self.real_owner_is_contact:
            return {
                'name': self.real_owner_name,
                'address': self.real_owner_addr,
                'phone': self.real_owner_phone,
                'email': self.real_owner_email,
                'paiement_info': self.real_owner_paiement_info,
            }
        else:
            return {
                'name': self.owner.get_full_name(),
                'address': self.owner.get_address(),
                'phone': self.owner.phone,
                'email': self.owner.email,
                'paiement_info': self.owner.paiement_info,
            }

    @property
    def icon(self):
        return staticfiles_storage.url('img/geo-pointer.svg')

    @property
    def center(self):
        if 'trees' in getattr(self, '_prefetched_objects_cache', {}):
            tree_points = [t.point for t in self.trees.all()]
        else:
            tree_points = list(self.trees.all().values_list('point', flat=True))
        if tree_points:
            return MultiPoint(tree_points, srid=APP_SRID).centroid
        else:
            # Fallback to municipality center
            return self.municipality.center

    def can_view(self, user):
        return self.is_public or self.can_edit(user)

    def can_edit(self, user):
        return self.owner == user or user.is_superuser


class FruitCategory(TranslatableModel):
    translations = TranslatedFields(
        name = models.CharField(max_length=30),
    )
    color = RGBColorField(_("Color"), blank=True)

    def __str__(self):
        return self.name


class TreeSpecies(TranslatableModel):
    category = models.ForeignKey(FruitCategory, on_delete=models.CASCADE)
    color = RGBColorField(_("Color"), blank=True)

    translations = TranslatedFields(
        name = models.CharField(max_length=200),
        fruit = models.CharField(max_length=50),
    )

    def __str__(self):
        return self.name


REQ_CHOICES = (
    ('easy', _("Easy")),
    ('middle', _("Medium")),
    ('hard', _("Hard")),
)

USAGE_CHOICES = (
    ('dessert', _('dessert fruit')),
    ('juice', _('juice fruit')),
    ('dried', _('dried fruit')),
    ('distil', _('distillation fruit')),
    ('preserve', _('preserved fruit')),
)

class Tree(models.Model):
    AVAILABILITY_CHOICES = (
        ('none', _("Not publicly available")),
        ('whole', _("The tree can be individually booked")),
        ('picking', _("The tree is part of a self-picking offer")),
    )

    updated = models.DateTimeField()
    orchard = models.ForeignKey(Orchard, on_delete=models.CASCADE, related_name='trees')
    species = models.ForeignKey(TreeSpecies, verbose_name=_("Species"), on_delete=models.PROTECT)
    variety = models.CharField(_("Variety"), max_length=200)
    variety_descr = models.TextField(_("Variety description"), blank=True)
    availability = models.CharField(
        _("Availability"), max_length=10, choices=AVAILABILITY_CHOICES, default='none',
    )
    point = gis_models.PointField(srid=APP_SRID, verbose_name=_("Location"))
    general_descr = models.TextField(_("General description"), blank=True, help_text=_(
        "The better the tree is described and characterized, the more chances "
        "this website will be able to attract clients for your orchard."
    ))
    pick_start = models.CharField(
        _("Start of picking period"), max_length=5, choices=YEAR_PERIOD_CHOICES, blank=True
    )
    pick_end = models.CharField(
        _("End of picking period"), max_length=5, choices=YEAR_PERIOD_CHOICES, blank=True
    )
    treatment = models.TextField(_("Tree treatments"), blank=True,
        help_text=_("Treatments done or planned for the tree."))
    price = models.SmallIntegerField(
        _("Price"), blank=True, null=True,

templates/collect/collecting.html
{% extends 'base.html' %}
{% load orchard %}

{% block extra_head %}
    {% include 'geo_headers.html' %}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="//code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <script src="{% static 'js/collect.js' %}"></script>
    <script>
        var orchardDetailsURL = "{% url 'orchard-map-details' 0 %}";
        var selectedIcon = "{% static 'img/geo-pointer-reversed.svg' %}";
        var startPoints = [];

        {% for item in orchards %}
        startPoints.push('{{ item.0|as_geojson }}');
        {% endfor %}
    </script>
{% endblock %}

{% block content %}

    {% include 'collect/hero.html' %}

    {% include 'collect/accordion.html' %}

    <div id="search-with-map" class="search-with-map">
        {% include 'collect/search-form.html' %}

        <div style="display: none;">
            <div id="map-popup" title="{% trans 'Details' %}"></div>
        </div>

        <div id="map"></div>
    </div>

    <div id="result-list" class="search-result-list" style="{% if search_form.is_bound %} display: block; {% else %} display: none; {% endif %}">
        <div class="container">
            <div class="row">
                <div class="col-12 col-sm-10 offset-sm-1 col-md-8 offset-md-2">
                    <div id="orchard-list" class="search-result-list__inside">
                        {% if search_form.is_bound %}{% include 'orchard_search_list.html' %}{% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include 'collect/save-form.html' %}

{% endblock %}

templates/collect/hero.html
<div class="site-hero has-image">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-4 d-flex justify-content-center">
                <img class="site-hero__image" src="{% static 'img/illu_suche.svg' %}">
            </div>
            <div class="col-12 col-md-8">
                <h2 class="site-hero__subtitle">{% trans 'Fruit searching' %}</h2>
                <h1 class="site-hero__title is-dark">{% trans 'Search for and find fruit in your area' %}</h1>

                <div class="site-hero__description">
                    <p>{% trans "On meinobstgarten.ch you will find fruit trees with ripe-for-picking fruits in your area. You can save your search and meinobstgarten.ch informs you as soon as any result is found matching your search. The closer the harvest date, the bigger your chances are." %}</p>
                </div>
                {% if not user.is_authenticated %}
                <div class="site-hero__btns">
                    <a href="{% url 'login' %}" class="btn">{% trans 'Log in' %}</a>
                    <br>
                    <a href="{% url 'create_account_user' %}" class="btn">{% trans 'Create a free account' %}</a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

templates/collect/save-form.html
<div id="savesearch-div" class="save-your-search" {% if not search_form.is_bound %}style="display: none;"{% endif %}>
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-10 offset-md-1">
                {% if user.is_authenticated %}
                    <p>{% trans 'You can <strong><a href="#" id="savesearch-link">save this search</a></strong> and regularly get informed about new results.' %}</p>
                    <form id="savesearch-form" class="hidden" method="post">{% csrf_token %}
                        <div class="row">
                            <div class="col-12 col-sm-6">
                                <div class="input-group">
                                    <label for="id_name" class="input-group__label">{% trans 'Name:' %}</label>
                                    <input class="input-group__field" type="text" name="name" maxlength="200" required="" id="id_name">
                                </div>
                            </div>

                            <div class="col-12 col-sm-6">
                                <div class="input-group">
                                    <label for="id_name" class="input-group__label">{% trans 'Notification interval:' %}</label>
                                    <select class="input-group__field" name="interval" id="id_interval">
                                        <option value="" selected="">Never</option>
                                        <option value="daily">Daily</option>
                                        <option value="weekly">Weekly</option>
                                        <option value="monthly">Monthly</option>
                                    </select>
                                </div>
                            </div>
                        </div>

                        <input type="hidden" name="form_data" id="id_form_data">

                        <button class="btn" type="submit" formaction="{% url 'search-save' %}">{% trans 'Save Search' %}</button>
                    </form>
                {% else %}
                    {% url 'login' as login_url %}
                    <p>{% blocktrans %}You can save your searches and be alerted for new opportunities when you are <a href="{{ login_url }}">logged in</a>.{% endblocktrans %}</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>

templates/collect/search-form.html
{% load orchard %}
<div class="container">
    <div class="row search-with-map__form">
        <div class="col-12">
            <div class="search-with-map__inside">
                <h2 class="search-with-map__title">{% trans "Search" %}</h2>
                <form id="search-form" method="GET" action=".">
                    <div class="row">
                        <div class="col-12">
                            {{ search_form.typ|label_tag }}
                            {% for typ in search_form.typ.field.choices %}
                                <div class="input-group no-margin">
                                    <label for="id_{{ typ.0 }}" class="custom-checkbox">
                                        <input
                                            class="custom-checkbox__input"
                                            type="checkbox"
                                            id="id_{{ typ.0 }}"
                                            name="{{ search_form.typ.name }}"
                                            value="{{ typ.0 }}"
                                            {% if typ.0 in search_form.typ.value or not search_form.typ.value %} checked {% endif %}
                                        >
                                        <span class="custom-checkbox__label">{{ typ.1 }}</span>
                                    </label>
                                </div>
                            {% endfor %}
                        </div>

                        <div class="col-12 col-sm-6 col-md-4">
                            <div class="input-group">
                                {{ search_form.category|label_tag }}
                                <select id="id_category" name="{{ search_form.category.name }}" class="input-group__field">
                                    {% for fruit in search_form.category.field.choices %}
                                        <option value="{{ fruit.0 }}" {% if search_form.category.value|stringformat:'s' == fruit.0|stringformat:'s' %} selected {% endif %}>
                                            {% trans fruit.1 %}
                                        </option>
                                    {% endfor %}
                                </select>
                                {{ search_form.category.errors }}
                            </div>
                        </div>

                        <div class="col-12 col-sm-6 col-md-4">
                            <div class="input-group">
                                {{ search_form.from_loc|label_tag }}
                                <input id="id_from_loc" class="input-group__field ui-autocomplete-input"
                                       placeholder="{{ search_form.from_loc.label }}" type="text" name="{{ search_form.from_loc.name }}"
                                       autocomplete="off" value="{{ search_form.from_loc.value|default:'' }}"
                                       data-url="{% url 'location-search' %}">
                                {{ search_form.from_loc.errors }}
                            </div>
                        </div>

                        <div class="col-12 col-sm-6 col-md-4">
                            <div class="input-group">
                                {{ search_form.radius|label_tag }}
                                <input
                                    placeholder="{% trans 'km' %}"
                                    class="input-group__field"
                                    type="number"
                                    name="{{ search_form.radius.name }}"
                                    min="0"
                                    id="id_radius"
                                    value="{{ search_form.radius.value|default:'' }}"
                                >
                                {{ search_form.radius.errors }}
                            </div>
                        </div>

                        <div class="col-12">
                            <div class="input-group no-margin">
                                <label for="id_only_avail" class="custom-checkbox">
                                    <input
                                        class="custom-checkbox__input"
                                        type="checkbox"
                                        id="id_only_avail"
                                        name="{{ search_form.only_avail.name }}"
                                        {% if search_form.only_avail.value %} checked {% endif %}
                                    >
                                    <span class="custom-checkbox__label">{{ search_form.only_avail.label }}</span>
                                </label>
                            </div>
                            <div class="input-group no-margin">
                                <label for="id_only_pickable" class="custom-checkbox">
                                    <input
                                        class="custom-checkbox__input"
                                        type="checkbox"
                                        id="id_only_pickable"
                                        name="{{ search_form.only_pickable.name }}"
                                        {% if search_form.only_pickable.value %} checked {% endif %}
                                    >
                                    <span class="custom-checkbox__label">{{ search_form.only_pickable.label}}</span>
                                </label>
                                <span class="helptext">{% trans "Outside of the fruit season, you'll get few results if you check this box." %}</span>
                            </div>
                        </div>

                        <div class="col-12">
                            <div id="result-count" class="mt2r message is-warning">{% if search_form.is_bound %}{% blocktrans count num=orchards|length %}Your search returned {{ num }} orchard.{% plural %}Your search returned {{ num }} orchards.{% endblocktrans %}{% endif %}</div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>