common/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.utils.translation import gettext_lazy as _

from accounts import views as accounts_views
from accounts.forms import PasswordResetForm
from locations import views as loc_views
from news import views as news_views
from orchard import views

urlpatterns = [
    path('login/', accounts_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/new_user/', accounts_views.CreateAccountView.as_view(typ='user'),
        name='create_account_user'),
    path('accounts/new_owner/', accounts_views.CreateAccountView.as_view(typ='owner'),
        name='create_account_owner'),
    path('accounts/v/<token>/', accounts_views.VerifyAccountView.as_view(),
        name='account_verification'),
    path('accounts/<int:pk>/edit/', accounts_views.EditAccountView.as_view(),
        name='edit_account'),
    path('accounts/<int:pk>/delete/', accounts_views.DeleteAccountView.as_view(),
        name='delete-account'),

    # Password reset views
    path('accounts/password_reset/',
        auth_views.PasswordResetView.as_view(
            template_name='accounts/password_reset_form.html', form_class=PasswordResetForm),
        name='password_reset'),
    path('accounts/password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('reset/done/',
        auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),

    path('accounts/<int:pk>/saved_search/', accounts_views.SavedSearchList.as_view(),
        name='savedsearch-list'),
    path('accounts/<int:pk>/bookings/', accounts_views.BookingsList.as_view(),
        name='bookings-list'),
    path('accounts/<int:pk>/productorders/', accounts_views.ProductOrdersList.as_view(),
        name='productorders-list'),
    path('i18n/setlang/<lang_code>/', accounts_views.set_language, name='set_language'),

    path('', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('about/taxes/', views.SimpleTemplateView.as_view(template_name='taxes.html', title=_("Gebührenreglement")),
        name='taxes'),
    path('about/impressum/', views.SimpleTemplateView.as_view(template_name='impressum.html', title="Impressum"),
        name='impressum'),
    path('about/safety/', views.SimpleTemplateView.as_view(template_name='safety.html', title=_("Safety Data Sheet")),
        name='safety'),

    path('map/', views.MapView.as_view(), name='map'),
    path('offer/', views.OfferView.as_view(), name='offer'),
    path('collect/', views.CollectView.as_view(), name='collect'),
    path('collect/save_search/', views.SearchSaveView.as_view(), name='search-save'),
    path('collect/save_search/delete/', views.SearchSaveDeleteView.as_view(),
        name='search-delete'),
    path('news/', news_views.NewsListView.as_view(), name='news'),
    path('orchard/new/', views.OrchardNewView.as_view(), name='orchard_new'),
    path('orchard/<int:pk>/', views.OrchardView.as_view(), name='orchard'),
    path('orchard/<int:pk>/sendmail/', views.OrchardContactSend.as_view(),
        name='orchard-sendmail'),
    path('orchard/<int:pk>/overview/', views.OrchardOverview.as_view(),
        name='orchard-overview'),
    path('orchard/<int:pk>/edit/', views.OrchardEditView.as_view(),
        name='orchard_edit'),
    path('orchard/<int:pk>/delete/', views.OrchardDeleteView.as_view(),
        name='orchard_delete'),

    # Orchard trees
    path('orchard/<int:pk>/tree/new/', views.TreeNewView.as_view(), name='tree_new'),
    path('orchard/<int:pk>/tree/<int:pk_tree>/', views.TreeDetailsView.as_view(),
        name='tree_details'),
    path('orchard/<int:pk>/tree/<int:pk_tree>/edit/', views.TreeEditView.as_view(),
        name='tree_edit'),
    path('orchard/<int:pk>/tree/<int:pk_tree>/copymodifs/', views.TreeCopyModifsView.as_view(),
        name='tree_copymodifs'),
    path('orchard/<int:pk>/tree/<int:pk_tree>/duplicate/', views.TreeDuplicateView.as_view(),
        name='tree_dup'),
    path('orchard/<int:pk>/tree/<int:pk_tree>/delete/', views.TreeDeleteView.as_view(),
        name='tree_delete'),

    # Orchard products
    path('orchard/<int:pk>/product/new/', views.ProductNewView.as_view(), name='product_new'),
    path('orchard/<int:pk>/product/<int:pk_product>/', views.ProductDetailView.as_view(),
        name='product_detail'),
    path('orchard/<int:pk>/map_details/', views.OrchardMapDetails.as_view(),
        name='orchard-map-details'),
    path('orchard/<int:pk>/product/<int:pk_product>/edit/', views.ProductEditView.as_view(),
        name='product_edit'),
    path('orchard/<int:pk>/product/<int:pk_product>/delete/', views.ProductDeleteView.as_view(),
        name='product_delete'),
    path('orchard/<int:pk>/productorder/<int:pk_order>/', views.ProductOrderDetailView.as_view(),
        name='productorder_detail'),
    path('products/', views.ProductListView.as_view(), name='product_list'),
    path('my_products/', views.ProductOwnView.as_view(), name='my-products'),
    path('my_orchards/', views.OrchardOwnView.as_view(), name='my-orchards'),

    path('tree/<int:pk>/map_details/', views.TreeMapDetails.as_view(),
        name='tree-map-details'),
    path('tree/<int:pk>/<int:year>/book/', views.TreeBookingView.as_view(),
        name='tree-book'),
    path('booking/delete/', views.BookingDeleteView.as_view(),
        name='booking-delete'),

    path('location_search/', loc_views.LocationSearchView.as_view(), name='location-search'),

    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    # Should be an Apache alias in production
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

orchard/models.py
import datetime
from collections import OrderedDict
from urllib.parse import urlencode

from django import forms
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.contrib.gis.db import models as gis_models
from django.contrib.gis.geos import MultiPoint
from django.contrib.postgres.fields import ArrayField
from django.contrib.staticfiles.storage import staticfiles_storage
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from colorful.fields import RGBColorField
from parler.models import TranslatableModel, TranslatedFields
from accounts.models import User
from locations.models import Location

APP_SRID = 2056  # Not to be changed lightly, as this would need migrations

YEAR_PERIOD_CHOICES = (
    ('01.01', _("Start of January")),
    ('01.15', _("Middle of January")),
    ('01.31', _("End of January")),
    ('02.01', _("Start of February")),
    ('02.15', _("Middle of February")),
    ('02.28', _("End of February")),
    ('03.01', _("Start of March")),
    ('03.15', _("Middle of March")),
    ('03.31', _("End of March")),
    ('04.01', _("Start of April")),
    ('04.15', _("Middle of April")),
    ('04.30', _("End of April")),
    ('05.01', _("Start of May")),
    ('05.15', _("Middle of May")),
    ('05.31', _("End of May")),
    ('06.01', _("Start of June")),
    ('06.15', _("Middle of June")),
    ('06.30', _("End of June")),
    ('07.01', _("Start of July")),
    ('07.15', _("Middle of July")),
    ('07.31', _("End of July")),
    ('08.01', _("Start of August")),
    ('08.15', _("Middle of August")),
    ('08.31', _("End of August")),
    ('09.01', _("Start of September")),
    ('09.15', _("Middle of September")),
    ('09.30', _("End of September")),
    ('10.01', _("Start of October")),
    ('10.15', _("Middle of October")),
    ('10.31', _("End of October")),
    ('11.01', _("Start of November")),
    ('11.15', _("Middle of November")),
    ('11.30', _("End of November")),
    ('12.01', _("Start of December")),
    ('12.15', _("Middle of December")),
    ('12.31', _("End of December")),
)

PAIEMENT_CHOICES = (
    ('adv', _('Advance paiement')),
    ('cash', _('Cash on site')),
)


class ArrayChoiceFormField(forms.TypedMultipleChoiceField):
    widget = forms.CheckboxSelectMultiple

    def __init__(self, *args, **kwargs):
        # Prevent the empty choice
        if kwargs['choices'] and kwargs['choices'][0][0] == '':
            kwargs['choices'] = kwargs['choices'][1:]
        super().__init__(*args, **kwargs)


class ChoiceArrayField(ArrayField):
    def formfield(self, **kwargs):
        # Patch from https://code.djangoproject.com/ticket/27704
        if self.base_field.choices and 'choices_form_class' not in kwargs:
            defaults = {
                'choices_form_class': ArrayChoiceFormField,
                'coerce': self.base_field.to_python,
            }
            defaults.update(kwargs)
            return self.base_field.formfield(**defaults)
        else:
            defaults = {
                'form_class': SimpleArrayField,
                'base_field': self.base_field.formfield(),
                'max_length': self.size,
            }
        defaults.update(kwargs)
        return super().formfield(**defaults)



class Photo(models.Model):
    image = models.ImageField(upload_to="photos")
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey()


class VisibleQuerySet(models.QuerySet):
    """visble(user) only shows public or user-owned orchards."""
    def visible(self, user):
        return self.filter(models.Q(is_public=True) | models.Q(owner__pk=user.pk))


class Orchard(models.Model):
    owner = models.ForeignKey(User, on_delete=models.PROTECT)
    name = models.CharField(_("Name"), max_length=100)
    is_public = models.BooleanField(_("This orchard is visible to the public"), default=True,
        help_text=_("By checking this box, the orchard and its products become visible "
                    "to the public. If it's unchecked, the orchard and its products are "
                    "\"private\" and no longer publicly visible."),
    )
    municipality = models.ForeignKey(Location, verbose_name=_("Municipality"),
        on_delete=models.PROTECT)
    description = models.TextField(_("Description"))
    real_owner_name = models.CharField(_("Name"), max_length=100, blank=True)
    real_owner_addr = models.TextField(_("Address"), blank=True)
    real_owner_phone = models.CharField(_("Phone"), max_length=30, blank=True)
    real_owner_email = models.EmailField(_('email address'), blank=True)
    real_owner_paiement_info = models.TextField(_("Paiement info"), blank=True,
        help_text=_("CCP, Bank account, IBAN… to receive paiements if you charge for fruits"))
    real_owner_is_contact = models.BooleanField(default=False)
    pick_details = models.TextField(_("Pick instructions"), blank=True,
        help_text=_("Describe here details about any available ladder, its look and location, "
                    "maybe an unlocking code, available containers, whether they can be took away, etc. "
                    "This text is only visible by people having booked picking a tree in this orchard.")
    )

    photos = GenericRelation(Photo)

    objects = VisibleQuerySet.as_manager()

    def __str__(self):
        return self.name + str(_(" (private)") if not self.is_public else "")

    def get_absolute_url(self):
        return reverse('orchard', args=[self.pk])

    def geojson(self, target_srid=None):
        center = self.center
        if target_srid and center.srid != target_srid:
            center.transform(target_srid)
        return {
            'type': 'Feature',
            'id': self.pk,
            'geometry': {
                'type': 'Point',
                'coordinates': center.coords,
            },
            'properties': {
                'pk': self.pk,
                'icon': self.icon,
            },
        }

    def get_contact(self):
        if self.real_owner_is_contact:
            return {
                'name': self.real_owner_name,
                'address': self.real_owner_addr,
                'phone': self.real_owner_phone,
                'email': self.real_owner_email,
                'paiement_info': self.real_owner_paiement_info,
            }
        else:
            return {
                'name': self.owner.get_full_name(),
                'address': self.owner.get_address(),
                'phone': self.owner.phone,
                'email': self.owner.email,
                'paiement_info': self.owner.paiement_info,
            }

    @property
    def icon(self):
        return staticfiles_storage.url('img/geo-pointer.svg')

    @property
    def center(self):
        if 'trees' in getattr(self, '_prefetched_objects_cache', {}):
            tree_points = [t.point for t in self.trees.all()]
        else:
            tree_points = list(self.trees.all().values_list('point', flat=True))
        if tree_points:
            return MultiPoint(tree_points, srid=APP_SRID).centroid
        else:
            # Fallback to municipality center
            return self.municipality.center

    def can_view(self, user):
        return self.is_public or self.can_edit(user)

    def can_edit(self, user):
        return self.owner == user or user.is_superuser


class FruitCategory(TranslatableModel):
    translations = TranslatedFields(
        name = models.CharField(max_length=30),
    )
    color = RGBColorField(_("Color"), blank=True)

    def __str__(self):
        return self.name


class TreeSpecies(TranslatableModel):
    category = models.ForeignKey(FruitCategory, on_delete=models.CASCADE)
    color = RGBColorField(_("Color"), blank=True)

    translations = TranslatedFields(
        name = models.CharField(max_length=200),
        fruit = models.CharField(max_length=50),
    )

    def __str__(self):
        return self.name


REQ_CHOICES = (
    ('easy', _("Easy")),
    ('middle', _("Medium")),
    ('hard', _("Hard")),
)

USAGE_CHOICES = (
    ('dessert', _('dessert fruit')),
    ('juice', _('juice fruit')),
    ('dried', _('dried fruit')),
    ('distil', _('distillation fruit')),
    ('preserve', _('preserved fruit')),
)

class Tree(models.Model):
    AVAILABILITY_CHOICES = (
        ('none', _("Not publicly available")),
        ('whole', _("The tree can be individually booked")),
        ('picking', _("The tree is part of a self-picking offer")),
    )

    updated = models.DateTimeField()
    orchard = models.ForeignKey(Orchard, on_delete=models.CASCADE, related_name='trees')
    species = models.ForeignKey(TreeSpecies, verbose_name=_("Species"), on_delete=models.PROTECT)
    variety = models.CharField(_("Variety"), max_length=200)
    variety_descr = models.TextField(_("Variety description"), blank=True)
    availability = models.CharField(
        _("Availability"), max_length=10, choices=AVAILABILITY_CHOICES, default='none',
    )
    point = gis_models.PointField(srid=APP_SRID, verbose_name=_("Location"))
    general_descr = models.TextField(_("General description"), blank=True, help_text=_(
        "The better the tree is described and characterized, the more chances "
        "this website will be able to attract clients for your orchard."
    ))
    pick_start = models.CharField(
        _("Start of picking period"), max_length=5, choices=YEAR_PERIOD_CHOICES, blank=True
    )
    pick_end = models.CharField(
        _("End of picking period"), max_length=5, choices=YEAR_PERIOD_CHOICES, blank=True
    )
    treatment = models.TextField(_("Tree treatments"), blank=True,
        help_text=_("Treatments done or planned for the tree."))
    price = models.SmallIntegerField(
        _("Price"), blank=True, null=True,

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% trans "My Orchard" %} {% block htitle %}{{ title }}{% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/refresh-main.css' %}">
    <script src="{% static 'admin/js/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/obstgarten.js' %}"></script>
    <script src="{% static 'js/canvi.js' %}"></script>
    {% block extra_head %}{% endblock %}
</head>

<body>
    <!-- Canvi -->
    {% include 'partials/canvi.html' %}

    <div class="js-canvi-content canvi-content">
        <!-- Header -->
        {% include 'partials/header.html' %}

        <main class="site-main">
            <!-- Breadcrumbs -->
            {% comment %}
                {% include 'partials/breadcrumbs.html' %}
            {% endcomment %}

            <!-- Messages -->
            {% if messages %}
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <div class="messages">
                                {% for message in messages %}
                                    <p{% if message.tags %} class="message is-{{ message.tags }}"{% endif %}>{{ message|linebreaksbr }}</p>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}

            <!-- Content -->
            {% block content %}{% endblock %}
        </main>

        <!-- Footer -->
        {% include 'partials/footer.html' %}
    </div>
</body>
</html>

templates/impressum.html
{% extends "base.html" %}

{% block content %}

<div class="generic-page">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-10 offset-md-1 col-lg-7">
                <h1 class="page-header">{% trans "Impressum" %}</h1>
            </div>
            <div class="col-12 col-md-10 offset-md-1 col-lg-7 entry-content">
                <h3>{% trans "Editor" %}</h3>
                <p>{% trans "Address:" %}<br>
                {% trans "meinobstgarten.ch" %}<br>
                c/o Wildbiss<br>
                Drosselweg 12<br>
                4242 Laufen<br>
                {% trans "Phone:" %} +41 (0)79 402 17 56<br>
                {% trans "Internet:" %} <a href="mailto:raphael.haener@meinobstgarten.ch">https://www.meinobstgarten.ch</a><br>
                <a href="mailto:raphael.haener@meinobstgarten.ch">info@meinobstgarten.ch</a>
                </p>

                <h3>{% trans "Open Source Project - GNU Affero General Public License" %}</h3>
                <p>{% blocktrans %}Die Plattform meinobstgarten.ch ist ein Open Source Projekt. Der Code der Plattform wurde unter der <a href="https://de.wikipedia.org/wiki/GNU_Affero_General_Public_License">GNU Affero General Public Lizenz</a> veröffentlicht.{% endblocktrans %}</p>

                <h3>{% trans "Urheberrecht, Markenrecht" %}</h3>
                <p>{% blocktrans %}Das Urheberrecht für sämtliche publizierten Inhalte liegt bei meinobstgarten.ch sowie dem Verfasser des Beitrags. Texte, Bilder, Audio- und Video-Dateien oder sonstige Inhalte dürfen nur privat oder mit Quellenangabe für redaktionelle Beiträge in den Medien verwendet werden. Jede andere, insbesondere kommerzielle Verwendung ist nur mit ausdrücklichem Einverständnis von meinobstgarten.ch erlaubt.{% endblocktrans %}</p>

                <h3>{% trans "Limitation of liability" %}</h3>
                <p>{% blocktrans %}Die Inhalte unserer Seiten wurden mit grösster Sorgfalt erstellt. Für die Richtigkeit, Vollständigkeit und Aktualität der Inhalte übernimmt meinobstgarten.ch keine Haftung. Ebenso lehnt sie jede Haftung für Schäden irgendwelcher Art ab, die durch die Benutzung der Website entstehen. Die auf unserer Website bereitgestellten Informationen dienen einzig Informationszwecken und deren Anwendung liegt in der Verantwortung der Nutzer. Externe Links sind klar als solche gekennzeichnet. Für den Inhalt der verlinkten Seiten sind ausschliesslich deren Betreiber verantwortlich.{% endblocktrans %}</p>

                <h3>{% trans "Project management" %}</h3>
                {% url 'about' as about %}
                <p>{% blocktrans %}See <a href="{{ about }}">"about us"</a>{% endblocktrans %}</p>

                <p><i>{% trans "Update on:" %} 31.12.2017</i></p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/orchard_edit.html
{% extends 'base.html' %}
{% load orchard %}

{% block extra_head %}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script type="text/javascript" src="//code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    {{ form.media }}
    <style>
        tr#tr-i_am_owner th * { display: none; }
        ul#id_i_am_owner { list-style-type: none; padding: 0; margin: 0; }
        tbody#real-owner { display: none; }
        textarea#id_real_owner_addr { height: 3em; }
        textarea#id_real_owner_paiement_info { height: 3em; }
    </style>
    <script type="text/javascript">
        function radioHandler (value) {
            // Display the real owner part only when the appropriate radio button is chosen
            document.querySelectorAll('[data-field^="real_owner"]').forEach(function (el) {
                if (value == 'True') {
                    el.style.display = 'none';
                } else {
                    el.style.display = 'block';
                }
            });
        }
        document.addEventListener("DOMContentLoaded", function(ev) {
            var radios = document.getElementsByName('i_am_owner');
            for (var i = radios.length; i--; ) {
                radios[i].addEventListener('change', function (ev) { radioHandler(this.value); });
                if (radios[i].checked) radioHandler(radios[i].value);
            }
            $('#id_municipality').autocomplete({source: "{% url 'location-search' %}", minLength: 2});
        });
    </script>
{% endblock %}

{% block content %}
<div class="generic-page">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-10 offset-md-1 col-lg-7">
                <h1 class="page-header">{% if view.mode == 'add' %}{% trans 'Add a new orchard' %}{% else %}{{ form.instance.name }}{% endif %}</h1>
            </div>

            <div class="col-12 col-md-10 offset-md-1 col-lg-7 entry-content">
                <form method="POST" enctype="multipart/form-data" action=".">
                    {% csrf_token %}

                    {% for field in form %}
                        {% include 'partials/form-loop.html' %}
                    {% endfor %}

                    {{ photosformset.management_form }}
                    {{ photosformset.non_form_errors }}

                    {% for form in photosformset %}
                        <div class="upload-form">
                            {% for field in form %}
                                <div class="form-input">
                                    {% if field|is_checkbox %}
                                        <label for="id_{{ field.name }}" class="custom-checkbox">
                                            <input class="custom-checkbox__input" type="checkbox" id="id_{{ field.name }}" name="{{ field.name }}" {% if field.value %} checked {% endif %}>
                                            <span class="custom-checkbox__label">{{ field.label|strip_colon }}</span>
                                        </label>
                                    {% else %}
                                        {{ field }}
                                    {% endif %}
                                </div>
                            {% endfor %}
                        </div>
                    {% endfor %}

                    <div class="form-input">
                        <button type="submit" class="btn">{% if view.mode == 'add' %}{% trans 'Create orchard' %}{% else %}{% trans 'Update orchard' %}{% endif %}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/orchard_line.html
{% if editable %}
    <span class="show-on-hover">
        <a href="{% url 'orchard_edit' orchard.pk %}"><img src="{% static 'admin/img/icon-changelink.svg' %}"></a>
        <input type="image" formaction="{% url 'orchard_delete' orchard.pk %}" src="{% static 'admin/img/icon-deletelink.svg' %}" alt="Delete orchard" onclick="return confirm('{% trans "Do you really want to delete this orchard?" %}');">
    </span>
{% endif %}

templates/taxes.html
{% extends "base.html" %}

{% block content %}
<div class="generic-page">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-10 offset-md-1 col-lg-7">
                <h1 class="page-header">{% trans "Gebührenreglement" %}</h1>
            </div>
            <div class="col-12 col-md-10 offset-md-1 col-lg-7 entry-content">
                {% include 'partials/taxes.html' %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/tree_booking_form.html
{% load i18n orchard %}

<fieldset>
<img class="closebox" src="{% static 'img/close_window.svg' %}" title="{% trans 'Close' %}">
<form class="booking" method="post" action="{% url 'tree-book' tree.pk year %}"
      data-confirm="{% trans 'Do you really want to book fruit collecting for this tree?' %}">
  {% csrf_token %}
    <span class="header">{% trans 'Quantity:' %}</span> {{ tree.fruit_quantity }}<br>
    <span class="header">{% trans 'Planned dates:' %}</span> {{ tree|pick_date_string:year }}<br>
    <span class="header">{% trans 'Price:' %}</span> {{ tree.price_string }}<br>
    {% url 'safety' as safetyurl %}

    <div class="input-group">
        <label for="safety_check" class="custom-checkbox">
            <input class="custom-checkbox__input" id="safety_check" type="checkbox" name="safety_check" required> 
            <span class="custom-checkbox__label">{% blocktrans %}I have read the <a href="{{ safetyurl }}">safety data sheet</a> on fruit collection{% endblocktrans %}</span>
        </label>
    </div>

    <button class="btn type="submit">{% trans 'Book' %}</button>
</form>
</fieldset>

templates/tree_details.html
{% extends "base.html" %}
{% load orchard thumbnail %}

{% block extra_head %}
  {% include "geo_headers.html" %}

<script type="text/javascript">
    {% for item in other_trees %}
    otherPoints.push('{{ item|as_geojson }}');
    {% endfor %}

    document.addEventListener("DOMContentLoaded", function(event) {
      bdnmap.init('map', ['{{ tree|as_geojson }}'], {resolution: 1, format: 'JSON', detailsOnHover: true});
    });
</script>
<style>
    div.map { height: 200px; width: 100%; }
</style>
{% endblock %}

{% block content %}

<div class="orchard-hero">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-10 offset-md-1 col-lg-7">
                  <h1 class="orchard-hero__title is-large">{{ tree.species }}, {{ tree.variety }}</h1>

                  <div class="orchard-hero_description entry-content">
                      <p><i>{{ tree.get_availability_display }}
                        {% if tree.availability == 'whole' and tree.price %}({{ tree.price }} CHF){% endif %}</i>
                      </p>
                      {% if tree.pick_start %}<p><b>{% trans 'Picking period:' %}</b> {{ tree.pick_date_string }}</p>
                      {% endif %}
                      {% if ystate and ystate.fruit_quant %}<p><b>{% trans 'Fruit quantity estimated for this year:' %}</b> {{ ystate.get_fruit_quant_display }}</p>
                      {% endif %}
                  </div>
            </div>
        </div>
    </div>
</div>


  <div id="map"></div>

  <div class="generic-page">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-10 offset-md-1 col-lg-7 entry-content">
                {% if tree.photos.count %}{% for photo in tree.photos.all %}
                    {% thumbnail photo.image "x80" as im %}<img src="{{ im.url }}">{% endthumbnail %}
                {% endfor %}{% endif %}

                {% if tree.general_descr %}<p>{{ tree.general_descr|safe }}</p>{% endif %}
                {% if tree.variety_descr %}<h3>{% trans 'Variety description' %}</h3>
                    <p>{{ tree.variety_descr|safe }}</p>
                {% endif %}
                {% if tree.treatment %}<h3>{% trans 'Tree treatments' %}</h3>
                    <p>{{ tree.treatment|safe }}</p>
                {% endif %}
                {% if tree.is_habitat %}<b>{% trans 'Habitat tree' %}</b>
                {% if tree.habitat_note %}<br>{{ tree.habitat_note }}{% endif %}
                {% endif %}
                {% if tree.req_level %}
                    <p>{% trans 'Requirement level:' %} {{ tree.get_req_level_display }}</p>
                {% endif %}
                {% if tree.usages %}
                    <p><b>{% trans 'Fruit usage(s):' %}</b> {{ tree.get_usages_display }}</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}